dataset:
  script_path: ../datasets/cats_dogs.py
models:
- "../artifacts/catdog_baseline/cifar10_baseline_20170416-1043-32.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0100-53.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0102-37.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0104-10.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0231-53.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0250-54.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0256-20.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0352-24.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0435-25.h5"
- "../artifacts/catdog_baseline/cifar10_baseline_20170417-0524-29.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False