dataset:
  script_path: ../datasets/cats_dogs.py
models:
- "../artifacts/catdog_baseline/catdog_baseline_20170507-0638-11.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170507-0527-55.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170507-0344-04.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170507-0231-27.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170507-0044-55.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170506-2312-13.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170506-2208-09.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170506-2051-29.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170506-1918-54.h5"
- "../artifacts/catdog_baseline/catdog_baseline_20170506-1751-11.h5"
evaluate:
  batch_size: 250
  batch_size_train: 1
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False