dataset:
  script_path: ../datasets/cats_dogs.py
  img_rows: 128
  img_cols: 128
models:
- "../artifacts/catdog_opt_train_es/catdog_opt_train_es_20170530-0913-59.h5"
- "../artifacts/catdog_opt_train_es/catdog_opt_train_es_20170530-1828-38.h5"
- "../artifacts/catdog_opt_train_es/catdog_opt_train_es_20170531-0812-52.h5"
evaluate:
  batch_size: 250
  batch_size_train: 4522
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False