dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_bs8/cifar100_bs8_20170418-1338-11.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170418-0838-35.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170418-0114-20.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170417-1917-43.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False