dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-1450-12.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-1543-34.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-1720-28.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-1825-56.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-1926-45.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-2019-54.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-2115-43.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-2229-38.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170511-2317-44.h5"
- "../artifacts/cifar100_sigmoid_neg/cifar100_sigmoid_neg_20170512-0022-14.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False