dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1223-57.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1345-04.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1441-51.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1553-12.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1657-48.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1814-15.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-1911-05.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-2008-43.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-2107-23.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170420-2204-59.h5"
evaluate:
  batch_size: 500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False