dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_nin/cifar100_nin_20170424-2003-19.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170424-2059-11.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170424-2152-32.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170424-2248-05.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170424-2353-28.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170425-0110-15.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170425-0205-24.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170425-0255-40.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170425-0413-10.h5"
- "../artifacts/cifar100_nin/cifar100_nin_20170425-0505-18.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False