dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1309-10.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1329-45.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1408-30.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1453-07.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1530-24.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1601-56.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1638-20.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1713-03.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1749-44.h5"
- "../artifacts/cifar100_opt_es_test_set/cifar100_opt_es_test_set_20170604-1825-55.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False