dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_tanh/cifar100_tanh_20170426-2133-41.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170426-2222-03.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170426-2311-10.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0002-59.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0109-38.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0217-52.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0334-33.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0425-26.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0523-02.h5"
- "../artifacts/cifar100_tanh/cifar100_tanh_20170427-0644-18.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False