dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-1617-12.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-1715-52.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-1810-44.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-1851-13.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-1940-09.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-2024-53.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-2109-32.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-2158-56.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-2256-28.h5"
- "../artifacts/cifar100_baseline/cifar100_baseline_20170419-2336-21.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False