dataset:
  script_path: ../datasets/cifar100_keras.py
model:
  script_path: ../models/baseline_relu_neg.py
models:
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170515-1935-56.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170515-2035-35.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170515-2144-17.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170515-2246-41.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170515-2347-56.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170516-0050-54.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170516-0222-41.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170516-0342-22.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170516-0454-10.h5"
- "../artifacts/cifar100_relu_neg/cifar100_relu_neg_20170516-0557-54.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False