dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0746-59.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0650-46.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0535-22.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0438-56.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0309-44.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0153-59.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170427-0044-07.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170426-2334-35.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170426-2238-19.h5"
- "../artifacts/cifar100_eos/cifar100_baseline_20170426-2134-51.h5"
evaluate:
  batch_size: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False