dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_seq3/cifar100_seq3.h5"
- "../artifacts/cifar100_seq3/cifar100_seq3-1.h5"
- "../artifacts/cifar100_seq3/cifar100_seq3-2.h5"
- "../artifacts/cifar100_seq3/cifar100_seq3-3.h5"
- "../artifacts/cifar100_seq3/cifar100_seq3-4.h5"
- "../artifacts/cifar100-models/cifar100-4.h5"
- "../artifacts/cifar100-models/cifar100-5.h5"
- "../artifacts/cifar100-models/cifar100-6.h5"
- "../artifacts/cifar100-models/cifar100-7.h5"
- "../artifacts/cifar100-models/cifar100-8.h5"
- "../artifacts/cifar100-models/cifar100-9.h5"
- "../artifacts/cifar100-models/cifar100-10.h5"
- "../artifacts/cifar100-models/cifar100-11.h5"
- "../artifacts/cifar100-models/cifar100-12.h5"
- "../artifacts/cifar100-models/cifar100-more-augmentation-2.h5"
- "../artifacts/cifar100-models/cifar100-more-aug-more-data.h5"
- "../artifacts/cifar100-models/cifar100-more-aug-more-data.h5"
- "../artifacts/cifar100_dense_keras/cifar100_dense.h5"
other:
- "../artifacts/cifar100-models/cifar100-more-augmentation.h5"
- "../artifacts/cifar100_thin_resnet/cifar100_thin_resnet_chk.h5"
- "../artifacts/cifar100-models/cifar100-2-new.h5"
- "../artifacts/cifar100-models/cifar100-1-new.h5"
bad:
- "../artifacts/cifar100-models/cifar100-13.h5"
- "../artifacts/cifar100-models/cifar100-1.h5"
- "../artifacts/cifar100-models/cifar100-2.h5"
- "../artifacts/cifar100-models/cifar100-3.h5"
- "../artifacts/cifar100-models/cifar100.h5"
- "../artifacts/cifar100_resnetpa/cifar100_resnetpa_chk.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 5
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0.2
    shear_range: 0.1
    channel_shift_range: 0.0
    featurewise_center: False
    zca_whitening: False