dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-1913-16.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-1953-05.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2018-54.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2045-49.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2140-55.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2225-32.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2247-42.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170415-2351-13.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170416-0029-24.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170416-0051-00.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False