dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1140-07.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1251-14.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1407-09.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1507-23.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1625-42.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1745-37.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-1926-40.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-2025-34.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-2221-28.h5"
- "../artifacts/cifar100_colortransformation/cifar100_colortransformation_20170422-2338-07.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False