dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-0858-45.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1008-13.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1117-44.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1251-02.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1403-54.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1515-40.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1617-42.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1731-08.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1839-01.h5"
- "../artifacts/cifar100_prelu/cifar100_prelu_20170426-1949-12.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False