dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170528-1147-04.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170528-1800-34.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170601-1128-23.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170601-1753-35.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170602-0034-27.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170602-0700-50.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170602-1438-27.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170602-2021-04.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170603-0203-38.h5"
- "../artifacts/cifar100_opt_reg001/cifar100_opt_reg001_20170603-0758-37.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False