dataset:
  script_path: ../datasets/cifar10_keras.py
models:
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0143-59.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0236-11.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0328-51.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0420-44.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0512-37.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0604-22.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0656-20.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0748-07.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0840-08.h5"
- "../artifacts/cifar10_opt_long/cifar10_opt_long_20170525-0931-56.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False