dataset:
  script_path: ../datasets/cifar100_keras.py
model:
  script_path: ../models/baseline_s_shape.py
models:
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1400-56.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1505-57.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1614-13.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1741-27.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1834-02.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-1925-33.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-2023-11.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-2108-08.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-2222-40.h5
- "../artifacts/cifar100_s_shape/cifar100_s_shape_20170512-2307-58.h5
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False