dataset:
  script_path: ../datasets/cifar10_keras.py
models:
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1334-55.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1419-42.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1523-58.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1608-53.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1707-45.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1810-24.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-1942-27.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-2046-51.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-2147-16.h5"
- "../artifacts/cifar10_opt/cifar10_opt_20170502-2244-16.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False