dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170420-2238-53.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170420-2320-24.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170420-2358-42.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0038-09.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0117-12.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0201-20.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0245-57.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0330-41.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0414-44.h5"
- "../artifacts/cifar100_baseline_pool_kernel/cifar100_baseline_pool_kernel_20170421-0503-25.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False