dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_bs16/cifar100_bs16_20170421-2230-30.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-0115-31.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-0354-29.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-0714-19.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-0917-46.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-1202-18.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-1414-08.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-1617-17.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-1932-29.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170422-2213-10.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False