dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_bs8/cifar100_bs8_20170421-1721-27.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170421-2238-10.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170422-0415-25.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170422-0724-26.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170422-1204-39.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170422-1547-31.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170422-2050-52.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170423-0119-41.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170423-0457-36.h5"
- "../artifacts/cifar100_bs8/cifar100_bs8_20170423-1002-45.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False