dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1616-03.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1656-11.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1730-31.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1823-04.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1857-44.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-1938-50.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-2019-53.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-2100-08.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-2140-14.h5"
- "../artifacts/cifar100_no_bn_p/cifar100_no_bn_p_20170423-2227-21.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False