dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_bs16/cifar100_bs16_20170417-1924-10.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170417-2233-41.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170418-0123-57.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170418-0450-38.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170418-0728-59.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170418-1043-25.h5"
- "../artifacts/cifar100_bs16/cifar100_bs16_20170418-1409-30.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False