dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_softmax/cifar100_softmax_20170427-1631-47.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170427-1803-40.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170427-1951-28.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170427-2206-57.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170427-2352-30.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170428-0116-27.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170428-0244-10.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170428-0416-08.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170428-0553-38.h5"
- "../artifacts/cifar100_softmax/cifar100_softmax_20170428-0734-20.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False