dataset:
  script_path: ../datasets/cifar100_keras.py
models:
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1004-11.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1136-09.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1316-16.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1510-49.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1632-06.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1752-05.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-1924-19.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-2116-50.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170422-2235-53.h5"
- "../artifacts/cifar100_bs32/cifar100_bs32_20170423-0020-14.h5"
evaluate:
  batch_size: 5000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False