dataset:
  script_path: ../datasets/cifar10_keras.py
models:
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170525-2314-42.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-0316-10.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-0710-10.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-1125-40.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-1443-26.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-1901-29.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170526-2229-46.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170527-0243-48.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170528-1017-37.h5"
- "../artifacts/cifar10_opt_train_es/cifar10_opt_train_es_20170528-1311-38.h5"
evaluate:
  batch_size: 5000
  batch_size_train: 4500
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False