dataset:
  script_path: ../datasets/gtsrb.py
models:
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0135-45.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0213-05.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0250-11.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0327-24.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0404-42.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0441-52.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0519-05.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0556-28.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0633-35.h5"
- "../artifacts/gtsrb_opt_long/gtsrb_opt_long_20170525-0710-55.h5"
evaluate:
  batch_size: 842
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False