dataset:
  script_path: ../datasets/gtsrb.py
models:
- "../artifacts/gtsrb_linear/gtsrb_linear_20170522-2032-41.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170522-2118-39.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170522-2217-59.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170522-2303-10.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170522-2347-54.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170523-0036-43.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170523-0123-49.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170523-0201-14.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170523-0252-41.h5"
- "../artifacts/gtsrb_linear/gtsrb_linear_20170523-0336-16.h5"
evaluate:
  batch_size: 842
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False