dataset:
  script_path: ../datasets/gtsrb.py
models:
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0040-26.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0113-16.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0137-31.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0207-01.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0232-46.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0256-54.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0316-24.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0342-45.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0412-30.h5"
- "../artifacts/gtsrb_softsign/gtsrb_softsign_20170524-0440-21.h5"
evaluate:
  batch_size: 842
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False