dataset:
  script_path: ../datasets/gtsrb.py
models:
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170523-2359-08.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0043-20.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0125-09.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0213-16.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0304-41.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0347-08.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0438-46.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0523-45.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0603-47.h5"
- "../artifacts/gtsrb_softmax/gtsrb_softmax_20170524-0644-18.h5"
evaluate:
  batch_size: 842
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False