dataset:
  script_path: ../datasets/gtsrb.py
models:
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1507-08.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1550-08.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1626-21.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1702-25.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1748-12.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1825-44.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1908-54.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-1954-47.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-2038-14.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline_20170601-2116-52.h5"
models-old:
- "../artifacts/gtsrb_baseline/gtsrb_baseline.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-1.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-2.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-3.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-4.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-5.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-6.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-7.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-8.h5"
- "../artifacts/gtsrb_baseline/gtsrb_baseline-9.h5"
evaluate:
  batch_size: 842
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False