dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_prelu/hasy_prelu_20170505-1622-43.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170505-1848-50.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170505-2054-18.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170505-2308-02.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-0135-33.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-0357-03.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-0625-12.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-0841-31.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-1052-56.h5"
- "../artifacts/hasy_prelu/hasy_prelu_20170506-1246-44.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False