dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_baseline/hasy_baseline.h5"
- "../artifacts/hasy_baseline/hasy_baseline-1.h5"
- "../artifacts/hasy_baseline/hasy_baseline-2.h5"
- "../artifacts/hasy_baseline/hasy_baseline-3.h5"
- "../artifacts/hasy_baseline/hasy_baseline-4.h5"
- "../artifacts/hasy_baseline/hasy_baseline-5.h5"
- "../artifacts/hasy_baseline/hasy_baseline-6.h5"
- "../artifacts/hasy_baseline/hasy_baseline-7.h5"
- "../artifacts/hasy_baseline/hasy_baseline-8.h5"
- "../artifacts/hasy_baseline/hasy_baseline-9.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False