dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_softsign/hasy_softsign_20170505-1623-27.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170505-1732-44.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170505-1906-12.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170505-2044-12.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170505-2208-36.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170505-2345-42.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170506-0132-36.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170506-0257-55.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170506-0437-39.h5"
- "../artifacts/hasy_softsign/hasy_softsign_20170506-0618-14.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False