dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_softmax/hasy_softmax_20170506-1751-11.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170506-2111-45.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170507-0042-14.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170507-0439-07.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170508-1006-47.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170508-1326-07.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170508-1641-04.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170508-2022-55.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170508-2323-21.h5"
- "../artifacts/hasy_softmax/hasy_softmax_20170509-0239-52.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False