dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_relu/hasy_relu_20170504-1824-53.h5"
- "../artifacts/hasy_relu/hasy_relu_20170504-2023-00.h5"
- "../artifacts/hasy_relu/hasy_relu_20170504-2151-51.h5"
- "../artifacts/hasy_relu/hasy_relu_20170504-2317-53.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0043-56.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0217-05.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0346-03.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0512-55.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0638-46.h5"
- "../artifacts/hasy_relu/hasy_relu_20170505-0812-00.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False