dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-0817-37.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-1033-15.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-1249-35.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-1442-47.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-1716-14.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-1942-45.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170507-2211-02.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170508-0033-44.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170508-0234-47.h5"
- "../artifacts/hasy_vlrelu/hasy_vlrelu_20170508-0458-59.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False