dataset:
  script_path: ../datasets/hasy.py
models:
- "../artifacts/hasy_linear/hasy_linear_20170504-0056-05.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-0436-08.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-0711-09.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-1010-40.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-1256-28.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-1524-45.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-1832-22.h5"
- "../artifacts/hasy_linear/hasy_linear_20170504-2120-29.h5"
- "../artifacts/hasy_linear/hasy_linear_20170505-0045-56.h5"
- "../artifacts/hasy_linear/hasy_linear_20170505-0406-27.h5"
evaluate:
  batch_size: 2124
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False