dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_linear/mnist_linear_20170503-0932-36.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1009-51.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1047-05.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1125-19.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1206-18.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1244-11.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1336-16.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1413-49.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1501-24.h5"
- "../artifacts/mnist_linear/mnist_linear_20170503-1552-37.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False