dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_softmax/mnist_softmax_20170503-0934-04.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1019-54.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1048-30.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1117-36.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1201-56.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1230-52.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1259-52.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1346-48.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1433-30.h5"
- "../artifacts/mnist_softmax/mnist_softmax_20170503-1502-04.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False