dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1638-03.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1702-58.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1736-02.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1752-18.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1816-05.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1839-53.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1858-21.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1923-26.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-1952-51.h5"
- "../artifacts/mnist_sigmoid/mnist_sigmoid_20170503-2021-16.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False