dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0014-15.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0045-47.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0114-11.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0140-59.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0205-44.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0240-54.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0314-01.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0344-17.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0412-50.h5"
- "../artifacts/mnist_tanh/mnist_tanh_20170504-0445-33.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False