dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-0932-31.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1002-44.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1033-03.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1103-18.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1133-32.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1203-49.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1234-08.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1304-30.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1334-45.h5"
- "../artifacts/mnist_opt_long/mnist_opt_long_20170525-1405-01.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False