dataset:
  script_path: ../datasets/mnist.py
models:
- "../artifacts/mnist_relu/mnist_relu_20170430-1521-16.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1540-47.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1614-38.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1633-13.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1702-18.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1724-50.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1745-15.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1813-12.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1847-16.h5"
- "../artifacts/mnist_relu/mnist_relu_20170430-1915-58.h5"
evaluate:
  batch_size: 10000
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False