dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1146-41.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1205-21.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1220-03.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1234-47.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1246-20.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1301-34.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1323-24.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1338-24.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1356-02.h5"
- "../artifacts/stl10_tanh/stl10_tanh_20170517-1413-57.h5"
evaluate:
  batch_size: 500
  batch_size_train: 675
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False