dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_opt/stl10_opt_20170501-1224-03.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1212-56.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1212-56.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1148-06.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1129-31.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1109-57.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1058-50.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1041-16.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-1020-57.h5"
- "../artifacts/stl10_opt/stl10_opt_20170501-0943-20.h5"
evaluate:
  batch_size: 500
  batch_size_train: 4050
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False