dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-0932-53.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1102-31.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1248-02.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1414-29.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1544-52.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1718-08.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-1835-40.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-2012-28.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-2153-47.h5"
- "../artifacts/stl10_opt_train_es/stl10_opt_train_es_20170602-2327-17.h5"
evaluate:
  batch_size: 500
  batch_size_train: 4050
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False