dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_softsign/stl10_softsign_20170516-1827-13.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-1841-29.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-1904-25.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-1919-01.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-1946-20.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-2010-35.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-2036-42.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-2059-23.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-2114-38.h5"
- "../artifacts/stl10_softsign/stl10_softsign_20170516-2129-27.h5"
evaluate:
  batch_size: 500
  batch_size_train: 675
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False