dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0131-51.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0207-38.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0243-15.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0318-52.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0354-36.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0430-19.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0506-02.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0541-42.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0617-20.h5"
- "../artifacts/stl10_opt_long/stl10_opt_long_20170525-0653-01.h5"
evaluate:
  batch_size: 500
  batch_size_train: 4050
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False