dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_softmax/stl10_softmax_20170514-2349-10.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0030-18.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0114-20.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0202-30.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0254-03.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0340-18.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0428-43.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0525-28.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0608-15.h5"
- "../artifacts/stl10_softmax/stl10_softmax_20170515-0700-56.h5"
evaluate:
  batch_size: 500
  batch_size_train: 675
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False