dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1008-20.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1021-51.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1036-28.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1057-50.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1128-19.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1156-10.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1210-41.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1234-20.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1258-57.h5"
- "../artifacts/stl10_vlrelu/stl10_vlrelu_20170508-1318-16.h5"
evaluate:
  batch_size: 500
  batch_size_train: 675
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False