dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1238-41.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1259-54.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1322-01.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1344-09.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1407-07.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1429-28.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1451-03.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1517-06.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1538-43.h5"
- "../artifacts/stl10_baseline/stl10_baseline_20170420-1601-13.h5"
evaluate:
  batch_size: 810
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False