dataset:
  script_path: ../datasets/stl10.py
models:
- "../artifacts/stl10_relu/stl10_relu_20170514-2322-45.h5"
- "../artifacts/stl10_relu/stl10_relu_20170514-2343-28.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-0001-12.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-1938-40.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-1952-56.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-2015-22.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-2030-33.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-2049-11.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-2104-07.h5"
- "../artifacts/stl10_relu/stl10_relu_20170515-2125-38.h5"
evaluate:
  batch_size: 500
  batch_size_train: 675
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False