dataset:
  script_path: ../datasets/svhn.py
models:
- "../artifacts/svhn_baseline/svhn_baseline_20170412-1711-59.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170412-1728-50.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170412-1846-26.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170412-2127-42.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170412-2128-55.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170412-2357-53.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170413-0000-22.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170413-0023-51.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170413-0138-39.h5"
- "../artifacts/svhn_baseline/svhn_baseline_20170413-0341-49.h5"
evaluate:
  batch_size: 1627
  augmentation_factor: 1
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: False
    vertical_flip: False
    zoom_range: 0
    shear_range: 0.1
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False